// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhPwNwCILG0f_thEQjURESyVsYUdHh5pk',
    appId: '1:31779633480:web:a1b9a77577c0585e26db7d',
    messagingSenderId: '31779633480',
    projectId: 'taj-royal-c25cb',
    authDomain: 'taj-royal-c25cb.firebaseapp.com',
    storageBucket: 'taj-royal-c25cb.firebasestorage.app',
    measurementId: 'G-4S76KSSKJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoaQQ3F0l5JEoHnmxrFCbWyzdf-nanES4',
    appId: '1:31779633480:android:fca2198f9fb0ab6026db7d',
    messagingSenderId: '31779633480',
    projectId: 'taj-royal-c25cb',
    storageBucket: 'taj-royal-c25cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hjyVp6yzGBVqZ8rhQDWhm5KirYUNGq8',
    appId: '1:31779633480:ios:07d3ab0d8f7ff2ce26db7d',
    messagingSenderId: '31779633480',
    projectId: 'taj-royal-c25cb',
    storageBucket: 'taj-royal-c25cb.firebasestorage.app',
    iosBundleId: 'com.example.tajRoyalContract',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hjyVp6yzGBVqZ8rhQDWhm5KirYUNGq8',
    appId: '1:31779633480:ios:07d3ab0d8f7ff2ce26db7d',
    messagingSenderId: '31779633480',
    projectId: 'taj-royal-c25cb',
    storageBucket: 'taj-royal-c25cb.firebasestorage.app',
    iosBundleId: 'com.example.tajRoyalContract',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhPwNwCILG0f_thEQjURESyVsYUdHh5pk',
    appId: '1:31779633480:web:27d00d240f9b607326db7d',
    messagingSenderId: '31779633480',
    projectId: 'taj-royal-c25cb',
    authDomain: 'taj-royal-c25cb.firebaseapp.com',
    storageBucket: 'taj-royal-c25cb.firebasestorage.app',
    measurementId: 'G-1ZDNQXQ16S',
  );
}
